//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADVICE
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_Text
    {
        public int id { get; set; }
        public string Test { get; set; }
        public Nullable<int> Time { get; set; }
    }
}
